name: Run API Evaluation

on:
  push:
    branches:
      - main
    paths:
      - 'run-docker.sh'
      - 'evalplus/**'
      - 'ci/**'
      - 'Dockerfile'
      - '.github/workflows/run-docker.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'run-docker.sh'
      - 'evalplus/**'
      - 'ci/**'
      - 'Dockerfile'
      - '.github/workflows/run-docker.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-api-eval:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Available Model
        id: get_model
        env:
          MODEL_URL: ${{ vars.MODEL_URL }}
          MODEL_API_KEY: ${{ secrets.MODEL_API_KEY }}
        run: |
          echo "Fetching available models from $MODEL_URL/models"
          RESPONSE=$(curl -s "$MODEL_URL/models" -H "Authorization: Bearer $MODEL_API_KEY")
          echo "API Response: $RESPONSE"
          
          DATA_LENGTH=$(echo "$RESPONSE" | jq -r '.data | length')
          if [ "$DATA_LENGTH" = "null" ] || [ "$DATA_LENGTH" = "0" ]; then
            echo "Error: No models available in the data array"
            exit 1
          fi
          
          SELECTED_MODEL=$(echo "$RESPONSE" | jq -r '.data[0].id')
          
          if [ "$SELECTED_MODEL" = "null" ] || [ -z "$SELECTED_MODEL" ]; then
            echo "Error: Could not extract model ID from API response"
            exit 1
          fi
          
          echo "Selected model: $SELECTED_MODEL"
          echo "model_name=$SELECTED_MODEL" >> $GITHUB_OUTPUT

      - name: Run API evaluation script
        run: |
          ./run-docker.sh --model-name ${{ steps.get_model.outputs.model_name }} \
              --model-url ${{ vars.MODEL_URL }} \
              --model-api-token ${{ secrets.MODEL_API_KEY }} \
              --dataset humaneval \
              --ci
          ./run-docker.sh --model-name ${{ steps.get_model.outputs.model_name }} \
              --model-url ${{ vars.MODEL_URL }} \
              --model-api-token ${{ secrets.MODEL_API_KEY }} \
              --dataset mbpp \
              --ci

      - name: Output result
        run: |
          echo "# API Evaluation Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          ls -alh evalplus_results/*/*_results.json
          for json_file in evalplus_results/*/*_results.json; do
            if [ -f "$json_file" ]; then
              echo "Found result JSON file: $json_file"
              # Print the dataset name as header (first directory after evalplus_results)
              echo "## \`$(echo "$json_file" | cut -d'/' -f2)\`" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY

              # Print the file content in a code block
              echo '```json' >> $GITHUB_STEP_SUMMARY
              cat "$json_file" | jq >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY

              echo -e "\n" >> $GITHUB_STEP_SUMMARY
            fi
          done
